name: Validate DE commit messages

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    uses: minhazalam/data-engineering-interview-prep/.github/workflows/validate-de-commit-messages.yml@1fe4838abed2fefeb5e118eb713e1439e9a328e9
    with:
      base: ${{ github.event.pull_request.base.sha }}
      head: ${{ github.event.pull_request.head.sha }}
